
name: Cytex Scan
on:
  push:
    branches: ["master", "main"]
jobs:
  analyze:
    name: Code analysis
    runs-on: ubuntu-latest
    steps:
#       - run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
#       - run: python3 -m pip install semgrep
#       - run: python3 -m pip install pipreqs
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install pipreqs
        run: pip install pipreqs

      - name: Generate requirements.txt
        run: |
          if [ ! -f requirements.txt ]; then
            pipreqs .
          fi
#       - run: pipreqs --force .
      - run: grype dir:. -o json
      - run: semgrep --config=auto . --json
