# name: Semgrep
# on:
#   workflow_dispatch: {}
#   pull_request: {}
#   push:
#     branches:
#       - main
#       - master
#     paths:
#       - .github/workflows/semgrep.yml
#   schedule:
#     # random HH:MM to avoid a load spike on GitHub Actions at 00:00
#     - cron: '38 0 * * *'
# jobs:
#   semgrep:
#     name: semgrep/ci
#     runs-on: ubuntu-20.04
#     env:
#       SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
#     container:
#       image: returntocorp/semgrep
#     if: (github.actor != 'dependabot[bot]')
#     steps:
#       - uses: actions/checkout@v3
#       - run: semgrep ci


name: Semgrep

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" , "master"]
  schedule:
    - cron: '27 18 * * 3'

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout project source
      - uses: actions/checkout@v3

      # Scan code using project's configuration on https://semgrep.dev/manage
      - uses: returntocorp/semgrep-action@fcd5ab7459e8d91cb1777481980d1b18b4fc6735
        with:
          publishToken: ${{ secrets.SEMGREP_NASIR_TOKEN }}
          publishDeployment: ${{ secrets.SEMGREP_DEPLOYMENT_ID }}
          generateSarif: "1"

      # Upload SARIF file generated in previous step
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()
